### ISSUE TITLE
Gérer l'authentification Firebase

### ISSUE THREAD

**Issue by mbernardeau** [mbernardeau/Road-to-Russia-2018#1]
Proposer une authentification avec Firebase:

- [x] Google
- [x] Facebook
- [x] Stocker les infos utilisateurs dans la BDD
- [x] Limiter l'accès en écriture seulement à ses propres données
- [x] Afficher le contact dans la barre de menu
- [x] Offrir la possibilité de se déconnecter
- [x] Routes protégées

**Comment by naustra** [comment]
Ça sera juste pour nous non ? 
Google, ça me va.
