### ISSUE TITLE
Placer les matchs de 2018

### ISSUE THREAD

**Issue by mbernardeau** [mbernardeau/Road-to-Russia-2018#2]
- [x] Définir la structure dans firebase
- [x] Importer les équipes, stades, matchs
- [x] Créer les règles de sécurité (section limitées en écriture)
- [ ] Mettre à jour les avec les vrais pays quand les qualifs seront terminées (14 novembre 2017)

**Comment by naustra** [comment]
Tu veux dire quoi par règles de sécurité ?

**Comment by mbernardeau** [comment]
Un utilisateur qui n'est pas admin ne doit pas pouvoir modifier ces informations
C'est le fichier `firebase-rules` qui permet de faire ça

**Comment by naustra** [comment]
Dans la branche match-2018, j'ai mis à jour l'excel pour les matchs et le réglement pour info
